# -*- coding: utf-8 -*-
"""graph1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15JoJ0grf5a-rjuJ4SfD34DgwspxFcZJz
"""

import matplotlib.pyplot as plt
import numpy as np

# Text sizes and corresponding times for each algorithm (use actual output from C program)
text_sizes = [1000, 10000, 100000, 1000000]
naive_times = [0.04, 0.22, 2.1, 20.1]  # Example times, replace with actual
kmp_times = [0.02, 0.15, 1.5, 15.0]    # Example times, replace with actual
rabin_karp_times = [0.03, 0.18, 1.8, 17.5]  # Example times, replace with actual

# Plotting
plt.figure(figsize=(10, 6))
plt.plot(text_sizes, naive_times, label='Naive', marker='o', linestyle='-', color='b')
plt.plot(text_sizes, kmp_times, label='KMP', marker='o', linestyle='-', color='g')
plt.plot(text_sizes, rabin_karp_times, label='Rabin-Karp', marker='o', linestyle='-', color='r')

plt.xlabel('Text Size')
plt.ylabel('Time (seconds)')
plt.title('String Matching Algorithms Performance')
plt.legend()
plt.grid(True)
plt.xscale('log')  # Log scale for better visualization
plt.yscale('log')  # Log scale for better visualization
plt.show()