# -*- coding: utf-8 -*-
"""graph1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15JoJ0grf5a-rjuJ4SfD34DgwspxFcZJz
"""

import matplotlib.pyplot as plt
import numpy as np

# Sample data: Replace with the actual data from your C program
items = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]
capacities = [50, 100, 150, 200, 250, 300, 350, 400, 450, 500]
dp_times = [0.001, 0.002, 0.003, 0.004, 0.005, 0.006, 0.007, 0.008, 0.009, 0.010]
bt_times = [0.003, 0.004, 0.005, 0.007, 0.008, 0.010, 0.012, 0.014, 0.016, 0.018]
bnb_times = [0.001, 0.002, 0.003, 0.004, 0.005, 0.006, 0.007, 0.008, 0.009, 0.010]

# Create the plot
plt.figure(figsize=(10, 6))

# Plot each algorithm's performance
plt.plot(items, dp_times, label='Dynamic Programming', marker='o', linestyle='-', color='b')
plt.plot(items, bt_times, label='Backtracking', marker='o', linestyle='-', color='g')
plt.plot(items, bnb_times, label='Branch and Bound (Greedy)', marker='o', linestyle='-', color='r')

# Adding titles and labels
plt.xlabel('Number of Items')
plt.ylabel('Time (seconds)')
plt.title('Knapsack Problem: Algorithm Comparison')
plt.legend()
plt.grid(True)
plt.xscale('log')
plt.yscale('log')

# Show the plot
plt.show()