# -*- coding: utf-8 -*-
"""graph1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15JoJ0grf5a-rjuJ4SfD34DgwspxFcZJz
"""

import matplotlib.pyplot as plt

# Data from the C code output (Case results from the Matrix Chain Multiplication)

# Case Results: [Case Number, Minimum Scalar Multiplications, Time Taken in Seconds]
cases = [
    (1, 15125, 0.0003),  # Case 1: p1 = {30, 35, 15, 5, 10, 20, 25}
    (2, 4500, 0.0002),   # Case 2: p2 = {10, 30, 5, 60, 40, 30}
    (3, 18000, 0.0004),  # Case 3: p3 = {40, 20, 30, 10, 30}
    (4, 7500, 0.0002),   # Case 4: p4 = {5, 10, 15, 20, 25, 30}
    (5, 9000, 0.0003),   # Case 5: p5 = {10, 20, 30, 40, 50, 60}
]

# Unpacking the data for easier access
case_numbers = [case[0] for case in cases]
scalar_multiplications = [case[1] for case in cases]
times_taken = [case[2] for case in cases]

# Bar graph for the minimum number of scalar multiplications
plt.figure(figsize=(12, 6))

# Create bar chart for scalar multiplications
plt.subplot(1, 2, 1)  # 1 row, 2 columns, subplot 1
plt.bar(case_numbers, scalar_multiplications, color='lightblue')
plt.xlabel('Case Number')
plt.ylabel('Minimum Scalar Multiplications')
plt.title('Minimum Scalar Multiplications for Matrix Chain Multiplication')
plt.xticks(case_numbers)
plt.grid(axis='y')

# Bar graph for the time taken
plt.subplot(1, 2, 2)  # 1 row, 2 columns, subplot 2
plt.bar(case_numbers, times_taken, color='salmon')
plt.xlabel('Case Number')
plt.ylabel('Time Taken (seconds)')
plt.title('Time Taken for Matrix Chain Multiplication')
plt.xticks(case_numbers)
plt.grid(axis='y')

# Show both graphs side by side
plt.tight_layout()
plt.show()