# -*- coding: utf-8 -*-
"""graph1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15JoJ0grf5a-rjuJ4SfD34DgwspxFcZJz
"""

import matplotlib.pyplot as plt

# Data from the C code output (values obtained by Greedy and Dynamic Programming approaches)
# These are example values. Replace with actual results from running the C code.
methods = ['Greedy', 'Dynamic Programming']
values = [180.0, 220]  # Example values from both approaches. Modify based on actual results.

# Create a bar chart comparing the total value obtained by each approach
plt.figure(figsize=(8, 6))

plt.bar(methods, values, color=['lightblue', 'lightcoral'])

# Adding titles and labels
plt.title('0/1 Knapsack Problem: Greedy vs Dynamic Programming', fontsize=14)
plt.xlabel('Approach', fontsize=12)
plt.ylabel('Total Value Obtained', fontsize=12)

# Display the values on top of the bars
for i, v in enumerate(values):
    plt.text(i, v + 5, f"{v}", ha='center', va='bottom', fontsize=12)

# Show gridlines and make the plot more readable
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Show the plot
plt.tight_layout()
plt.show()